apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iko.fullname" . }}
  labels:
    {{- include "iko.labels" . | nindent 4 }}
data:
  # Spring Boot configuratie
  SERVER_PORT: {{ .Values.settings.iko.serverPort | quote }}
  
  # Database configuratie
  SPRING_DATASOURCE_URL: {{ .Values.settings.spring.datasource.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.settings.spring.datasource.username | quote }}
  SPRING_DATASOURCE_DRIVERCLASSNAME: {{ .Values.settings.spring.datasource.driverClassName | quote }}
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: {{ .Values.settings.spring.jpa.properties.hibernateDialect }}
  
  # OAuth2 en Security configuratie
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI: {{ printf "%s/realms/%s" .Values.settings.keycloak.authServerURL .Values.settings.keycloak.realm | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTID: {{ .Values.settings.keycloak.clientID | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: {{ printf "%s/realms/%s" .Values.settings.keycloak.authServerURL .Values.settings.keycloak.realm | quote }}
